### ISSUE TITLE
Support for php 8.2

### ISSUE THREAD

**Issue by JS-Media-Creation** [greenrivers/grav-plugin-webp#9]
I would love to use the webp plugin, but it doesn't work for me. My suggestion is that it doesn't support php 8.2 but if you've got other suggestions, I'd love to let me know.

I'm running the latest [linuxserver docker-grav image](https://github.com/linuxserver/docker-grav) and installed the requirements with the help from [here](https://github.com/linuxserver/docker-grav/issues/38#issuecomment-1674064744)

I made the unit test and this is the output:

```
Unit Tests (6) -------------------------------------------------------------------------------------------------------------------------------------
E ImageTest: Get image data (0.02s)
E ImageTest: Get image data from cli (0.00s)
✔ ImageTest: Get webp path (0.00s)
✔ ImageTest: Get webp dir (0.00s)
✔ ViewTest: Get jpg image extension (0.00s)
✔ ViewTest: Get webp image extension (0.00s)
----------------------------------------------------------------------------------------------------------------------------------------------------


Time: 203 ms, Memory: 4.00 MB

There were 2 errors:

---------
1) ImageTest: Get image data
 Test  tests/unit/Helper/ImageTest.php:testGetImageData
                                                                           
  [ParseError] syntax error, unexpected token "match", expecting variable  
                                                                           
#1  /config/www/user/plugins/webp/vendor/composer/ClassLoader.php:428
#2  /config/www/user/plugins/webp/tests/unit/Helper/ImageTest.php:37
#3  /config/www/user/plugins/webp/vendor/bin/codecept:117

---------
2) ImageTest: Get image data from cli
 Test  tests/unit/Helper/ImageTest.php:testGetImageDataFromCli
                                                                           
  [ParseError] syntax error, unexpected token "match", expecting variable  
                                                                           
#1  /config/www/user/plugins/webp/vendor/composer/ClassLoader.php:428
#2  /config/www/user/plugins/webp/tests/unit/Helper/ImageTest.php:63
#3  /config/www/user/plugins/webp/vendor/bin/codecept:117

ERRORS!
Tests: 6, Assertions: 4, Errors: 2.
```

**Comment by MajorKuprich** [comment]
Hello @Schw3pps,

The issue is related with [PHP EXIF package](https://www.php.net/manual/en/book.exif).
Plugin uses functions from these package, example: [exif_read_data()](https://github.com/greenrivers/grav-plugin-webp/blob/master/classes/Helper/Image.php#L88).
You must properly configure exif extension in [linuxserver/docker-grav image](https://github.com/linuxserver/docker-grav).
You can also check config by adding below code to **www/public/index.php** file.
```php
phpinfo();
exit();
``` 
Missing section in their config should looks less or more like that:
![exif config](https://i.imgur.com/I7Olbrf.png)

Some of unit tests aren't compatible with PHP8+ due to lack of backward compatibility in [Codeception 5](https://codeception.com/07-28-2022/codeception-5.html).

_This release is PHP 8+ only, so we are back on track with modern PHP. We are dropping support for PHPUnit < 9, and are technically ready for PHPUnit 10._

Regards

**Comment by JS-Media-Creation** [comment]
@MajorKuprich Thank you so much! Now it works as expected! :)
